### ISSUE TITLE
gls.py: no plot with python3

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/GLS#2]
Running
`python3 gls.py`
does not show a plot, but the message
```
Traceback (most recent call last):
  File "gls.py", line 460, in plot
    import matplotlib.pylab as mpl
  File "/usr/lib64/python3.4/site-packages/matplotlib/pylab.py", line 274, in <module>
    from matplotlib.pyplot import *
  File "/usr/lib64/python3.4/site-packages/matplotlib/pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python3.4/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
ImportError: No module named 'matplotlib.backends.backend_tkagg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gls.py", line 795, in <module>
    example()
  File "gls.py", line 762, in example
    exec(doctest.script_from_examples(Gls.__doc__))
  File "<string>", line 85, in <module>
  File "gls.py", line 462, in plot
    raise(ImportError("Could not import matplotlib.pylab."))
ImportError: Could not import matplotlib.pylab.
```

**Comment by mzechmeister** [comment]
It seems the problem is that `Tkinter` is not installed

```
Python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Tkinter'
```

**Comment by mzechmeister** [comment]
There are several backends in matplotlib:
```
>>> import matplotlib; matplotlib.use('')
...
ValueError: Unrecognized backend string "": valid strings are ['GTK', 'GTKAgg', 'GTKCairo', 'GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'gdk', 'pdf', 'pgf', 'ps', 'svg', 'template']
```
Since tkinter is not installed, the `TK` backends will not work. However, 'Qt4Agg' works in my case. This would require a modification of:
https://github.com/mzechmeister/GLS/blob/ba731d9de6d783b90e7c5db0dc613bcfb762dab5/python/gls.py#L458-L459

**Comment by mzechmeister** [comment]
Setting backends should be not a task in gls.py. Instead, these lines https://github.com/mzechmeister/GLS/blob/ba731d9de6d783b90e7c5db0dc613bcfb762dab5/python/gls.py#L458-L459
should be removed and the matplotlib backend should be properly set before:
https://stackoverflow.com/questions/4930524/how-can-i-set-the-backend-in-matplotlib-in-python
https://matplotlib.org/faq/usage_faq.html#what-is-a-backend
E.g. `export MPLBACKEND=Qt4Agg`

**Comment by mzechmeister** [comment]
The issue was again introduced in
https://github.com/mzechmeister/GLS/commit/e2ea9b3157ae54a5cc971da995b8cb804a0f6422#diff-289bc1d114eec80df0b8ca1afeea14b7

**Comment by mzechmeister** [comment]
This works now for me:
`MPLBACKEND=qt4agg python3 gls.py`
